services:
  db:
    image: pgvector/pgvector:pg16
    container_name: jobmatch-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: jobs
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./alter_sources.sql:/docker-entrypoint-initdb.d/alter_sources.sql:ro
  api:
    build:
      context: ../backend
    container_name: jobmatch-api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: jobs
    depends_on:
      - db
    ports:
      - "8000:8000"
  crawler:
    build:
      context: ../crawler
    container_name: jobmatch-crawler
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: jobs
      CRAWLER_USER_AGENT: "Mozilla/5.0 (compatible; JobMatchBot/0.1; +https://example.local)"
    depends_on:
      - db
    volumes:
      - ../crawler:/app
  discovery:
    build:
      context: ../discovery
    container_name: jobmatch-discovery
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: jobs
      SEARCH_PROVIDER: bing
      CRAWLER_USER_AGENT: "Mozilla/5.0 (compatible; JobMatchBot/0.2; +https://example.local)"
      # For live discovery, export in your shell:
      # SEARCH_API_KEY=... docker compose run --rm discovery python discovery.py
    depends_on:
      - db
    volumes:
      - ../crawler:/out
volumes:
  dbdata:
